apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: authenticated
spec:
  subjects:
  - user: "*"
    properties:
      request.auth.claims[role]: "*"
  roleRef:
    kind: ServiceRole
    name: "authenticated"

